# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 952f74e2cf1daf09e514b942cc041c279ff25d78e8fbe483999d25d9cd3aa3b1d1bfc3e15237c5a446aad8db1707f088dfb2455814b6955f3058e7db508b9fa1

test:
  secret_key_base: 0f82e06625bce803d953fefe83e09bc173ec9af168e47d58502d91d3f9b5e0afd97c992a4a6c90300506597f63f6a6ae1e76bc99a38b63851f9b1ad5fc246558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
